package main

import (
	"BackEnd/Controller"
	"BackEnd/Middleware"
	"BackEnd/Model"
	"fmt"
	"github.com/gin-gonic/gin"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
)

func main() {

	dsn := "root:123456@tcp(127.0.0.1:3306)/tttt?charset=utf8mb4&parseTime=True&loc=Local"
	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	//db, err := gorm.Open("mysql", "root:123456@/tttt?charset=utf8&parseTime=True&loc=Local")
	if err != nil {
		fmt.Println(err)
	}
	//defer db.Close()
	Model.CreateDatabase(db)
	r := gin.Default()
	r.Use(Middleware.Cors())
	r.POST("/test", Controller.Test)
	r.POST("/login", Controller.Auth(db))
	r.POST("/home", Middleware.JWTAuthMiddleWare(), Controller.HoeHandler)
	r.OPTIONS("/deleteHomework", Controller.ReturnOK)
	r.OPTIONS("/deleteClass", Controller.ReturnOK)
	r.OPTIONS("/quitCourse", Controller.ReturnOK)
	r.OPTIONS("/deleteStudent", Controller.ReturnOK)
	r.OPTIONS("/putStudent", Controller.ReturnOK)
	r.OPTIONS("/deletePunishment", Controller.ReturnOK)
	r.OPTIONS("/deleteTeacher", Controller.ReturnOK)
	r.OPTIONS("/putTeacher", Controller.ReturnOK)
	r.OPTIONS("/putAdmin", Controller.ReturnOK)
	r.OPTIONS("/deleteAdmin", Controller.ReturnOK)
	r.OPTIONS("/putTitle", Controller.ReturnOK)
	r.OPTIONS("/deleteTitle", Controller.ReturnOK)
	r.OPTIONS("/putPunishLevel", Controller.ReturnOK)
	r.OPTIONS("/deletePunishLevel", Controller.ReturnOK)
	r.OPTIONS("/putClassroom", Controller.ReturnOK)
	r.OPTIONS("/deleteClassroom", Controller.ReturnOK)
	r.OPTIONS("/deleteFacultySpecialtyDirection", Controller.ReturnOK)
	AuthGroup := r.Group("/",Middleware.Cors(),Middleware.JWTAuthMiddleWare())
	{
		AuthGroup.POST("/image", Controller.CheckedImage(db))
		AuthGroup.GET("/image", Controller.ImageSend)
		AuthGroup.GET("/imageTest", Controller.ImageSendTest)
		AuthGroup.GET("/homeworkJudgeList", Controller.HomeworkJudgeList(db))
		AuthGroup.GET("/getCourseList", Controller.GetCourseList(db))
		AuthGroup.GET("/getHomeworkList", Controller.GetHomeworkList(db))
		AuthGroup.DELETE("/deleteHomework", Controller.DeleteHomework(db))
		AuthGroup.POST("/postQuestion", Controller.PostQuestion(db))
		AuthGroup.GET("/getContentList", Controller.GetContentList(db))
		AuthGroup.POST("/createHomework", Controller.CreateHomework(db))
		AuthGroup.GET("/getNewHomeworkID", Controller.GetNewHomeworkID(db))
		AuthGroup.GET("/getQuestionList", Controller.GetQuestionList(db))
		AuthGroup.POST("/postHomework", Controller.PostHomework(db))
		AuthGroup.GET("/getReviewList", Controller.GetReviewList(db))
		AuthGroup.GET("/getClassesList", Controller.GetClassesList(db))
		AuthGroup.POST("/postNewClass", Controller.PostNewClass(db))
		AuthGroup.DELETE("/deleteClass", Controller.DeleteClass(db))
		AuthGroup.POST("/uploadClass", Controller.UploadClass(db))
		AuthGroup.POST("/postApply", Controller.PostApply(db))
		AuthGroup.GET("/getApply", Controller.GetApply(db))
		AuthGroup.POST("/operateApply", Controller.OperateApply(db))
		AuthGroup.POST("/validClassrooms", Controller.ValidClassrooms(db))
		AuthGroup.GET("/getClassSheet", Controller.GetClassSheet(db))
		AuthGroup.GET("/getAvailableCourses", Controller.GetAvailableCourses(db))
		AuthGroup.POST("/chooseCourse", Controller.ChooseCourse(db))
		AuthGroup.GET("/getChosenCourse", Controller.GetChosenCourse(db))
		AuthGroup.DELETE("/quitCourse", Controller.QuitCourse(db))
		AuthGroup.GET("/getStudentScore", Controller.GetStudentScore(db))
		AuthGroup.POST("/postScore", Controller.PostScore(db))
		AuthGroup.GET("/getScore", Controller.GetScore(db))
		AuthGroup.GET("/getUserInfo", Controller.GetUserInfo(db))
		AuthGroup.GET("/getDirectionList", Controller.GetDirectionList(db))
		AuthGroup.GET("/getTeacherList", Controller.GetTeacherList(db))
		AuthGroup.POST("/postDirection", Controller.PostDirection(db))
		AuthGroup.POST("/postTeacher", Controller.PostTeacher(db))
		AuthGroup.POST("/postPractice", Controller.PostPractice(db))
		AuthGroup.POST("/postIndependentPractice", Controller.PostIndependentPractice(db))
		AuthGroup.POST("/ApplyTeacher", Controller.ApplyTeacher(db))
		AuthGroup.GET("/getStudentList",Controller.GetStudentList(db))
		AuthGroup.DELETE("/deleteStudent",Controller.DeleteStudent(db))
		AuthGroup.PUT("/putStudent",Controller.PutStudent(db))
		AuthGroup.POST("/punishStudent",Controller.PunishStudent(db))
		AuthGroup.GET("/getPunishment",Controller.GetPunishment(db))
		AuthGroup.DELETE("/deletePunishment",Controller.DeletePunishment(db))
		AuthGroup.POST("/addStudent",Controller.AddStudent(db))
		AuthGroup.GET("/getPracticeInfo",Controller.GetPracticeInfo(db))
		AuthGroup.GET("/getTeacherListForManage",Controller.GetTeacherListForManage(db))
		AuthGroup.DELETE("/deleteTeacher",Controller.DeleteTeacher(db))
		AuthGroup.PUT("/putTeacher",Controller.PutTeacher(db))
		AuthGroup.POST("/addTeacher",Controller.AddTeacher(db))
		AuthGroup.GET("/getAdminList",Controller.GetAdminList(db))
		AuthGroup.DELETE("/deleteAdmin",Controller.DeleteAdmin(db))
		AuthGroup.PUT("/putAdmin",Controller.PutAdmin(db))
		AuthGroup.POST("/addAdmin",Controller.AddAdmin(db))
		AuthGroup.GET("/getTitleList",Controller.GetTitleList(db))
		AuthGroup.DELETE("/deleteTitle",Controller.DeleteTitle(db))
		AuthGroup.PUT("/putTitle",Controller.PutTitle(db))
		AuthGroup.POST("/addTitle",Controller.AddTitle(db))
		AuthGroup.GET("/getPunishLevelList",Controller.GetPunishLevelList(db))
		AuthGroup.DELETE("/deletePunishLevel",Controller.DeletePunishLevel(db))
		AuthGroup.PUT("/putPunishLevel",Controller.PutPunishLevel(db))
		AuthGroup.POST("/addPunishLevel",Controller.AddPunishLevel(db))
		AuthGroup.GET("/getClassroomList",Controller.GetClassroomList(db))
		AuthGroup.DELETE("/deleteClassroom",Controller.DeleteClassroom(db))
		AuthGroup.PUT("/putClassroom",Controller.PutClassroom(db))
		AuthGroup.POST("/addClassroom",Controller.AddClassroom(db))
		AuthGroup.GET("/getDirectionSpecialtyFacultyList",Controller.GetDirectionSpecialtyFacultyList(db))
		AuthGroup.POST("/addFacultySpecialtyDirection",Controller.AddFacultySpecialtyDirection(db))
		AuthGroup.DELETE("/deleteFacultySpecialtyDirection",Controller.DeleteFacultySpecialtyDirection(db))
		AuthGroup.POST("/isExpire")
	}
	r.Run(":9000")
}
